In [4]:
import pandas as pd

df = pd.read_csv('Refined_TK_dataver2.csv')  # adjust as needed
df.head()

,Detail of Gifts,Item Category,Name of Recipient,Affiliation,Date,Assessed Value,Retention Cost,Retained,Remarks
0,Two small silver\nBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen with\nink,Pen,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)\nfolding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nAf...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One Decoration\nPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes

In [5]:
df.sample(5)

,Detail of Gifts,Item Category,Name of Recipient,Affiliation,Date,Assessed Value,Retention Cost,Retained,Remarks
2054,One shield,NaN,"Mr. Shaukat Aziz, Prime\nMinister of Pakistan",Gen Mus,9/10/2007,0.0,0.0,Yes,Yes
675,One Wooden Flower\nVase,Decoration Pieces,"Mir Zafarullah Khan\nJamali, Prime Ministe...",Gen. Musharraf,6/5/2004,1800.0,0.0,Yes,Yes
2372,"One Wrist Watch\nwith pen, Tie &\nCufflin...",Watch,"Shahid Saleem Khan\nSr. Reporter,\nAssociat...",Media,5/4/2010,40000.0,4500.0,Yes,Yes
1097,One Golf Kit,NaN,"Mr. Shaukat Aziz, Prime\nMinister of Pakistan",Gen Mus,8/16/2005,1000.0,0.0,Yes,Yes
2161,Box containing model\n“Beijing Review”,NaN,"Mr. Asif Ali Zardari,\nPresident of Pakistan",PPP,10/23/2008,0.0,0.0,Yes,Yes